'use strict';

var DISPLAY_WIDTH = 85;
var DISPLAY_HEIGHT = 30;
var DISPLAY_FONT_SIZE = 18;

var WORLD_WIDTH = DISPLAY_WIDTH - 20;
var WORLD_HEIGHT = DISPLAY_HEIGHT;
var WORLD_LEVELS = 10;

var ROOM_WIDTH_MIN = 3;
var ROOM_WIDTH_MAX = 12;
var ROOM_HEIGHT_MIN = 3;
var ROOM_HEIGHT_MAX = 12;
var CORRIDOR_LENGTH_MIN = 1;
var CORRIDOR_LENGTH_MAX = 5;

var VIEW_DISTANCE = 91;

var UNSEEN_COLOR = '#333';
var SEEN_WALL_COLOR = '#222'
var SEEN_FLOOR_COLOR = '#17171c';
var VISIBLE_WALL_COLOR = '#222';
var VISIBLE_FLOOR_COLOR = '#111';
var ACTIVE_ENTITY_COLOR = '#133';
