'use strict';

var DISPLAY_WIDTH = 85;
var DISPLAY_HEIGHT = 30;
var DISPLAY_FONT_SIZE = 18;

var WORLD_WIDTH = DISPLAY_WIDTH - 20;
var WORLD_HEIGHT = DISPLAY_HEIGHT;
var WORLD_LEVELS = 10;

var VIEW_DISTANCE = 91;

var UNSEEN_COLOR = '#333';
var SEEN_WALL = '#222'
var SEEN_FLOOR = '#17171c';
var VISIBLE_WALL = '#222';
var VISIBLE_FLOOR = '#111';
